### ISSUE TITLE
Heroku error: no app.json

### ISSUE THREAD

**Issue by witeshadow** [phaxio/mailphax#1]

**Comment by jnankin** [comment]
Hi Chris.

Where are you seeing this error appear?  I'm able to hit the heroku button and launch the app from scratch.

Thanks,
Josh

**Comment by witeshadow** [comment]
I did it on my phone, so maybe that's why? 

On May 6, 2015 10:04:08 AM EDT, Josh Nankin notifications@github.com wrote:

> Hi Chris.
> 
> Where are you seeing this error appear?  I'm able to hit the heroku
> button and launch the app from scratch.
> 
> Thanks,
> Josh
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/phaxio/mailphax/issues/1#issuecomment-99476421

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jnankin** [comment]
Yes, confirmed.  The button does not seem to work on Heroku using a phone.  I'm not sure why, but that seems to be a heroku issue.  

I've reached out to heroku about this. 

Thanks,
Josh

**Comment by jnankin** [comment]
Internal ticket at heroku is Ticket #236391

**Comment by jnankin** [comment]
Here's the answer from Heroku:

Hi Josh,

Thanks for pasting the link, it contains the clue I was hoping for. We have a known issue that if you click the Deploy to Heroku from within the README.md, things will break. If you do this from the repository itself, ie. https://github.com/phaxio/mailphax, you should be fine. That said, this is an issue we are aware of and I just moved it to our To Do list so it'll be solved once and for all.

In the mean time, let me know if the workaround doesn't work for you.

Thanks,
Guðmundur Bjarni
